language: php

matrix:
  include:
    - php: 7.0
      env: DB=mysqli
  allow_failures:
    - php: 7.0
  fast_finish: true

env:
  global:
    - EXTNAME="phpbb/boardrules" # CHANGE name of the extension HERE
    - SNIFF="1"        # Should we run code sniffer on your code?
    - IMAGE_ICC="1"    # Should we run icc profile sniffer on your images?
    - EPV="1"          # Should we run EPV (Extension Pre Validator) on your code?
    - PHPBB_BRANCH="ticket/14036"

branches:
  only:
    - master
    - develop
    - /^develop-.*$/
    - /^release-.*$/

install:
  - travis_retry composer install --dev --no-interaction --prefer-source
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cd ../../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php
  - sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '5.3' ] && [ '$DB' = 'mysqli' ]; then phpBB/ext/$EXTNAME/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"
